# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ingress.name }}-delete
  labels:
    app: {{ .Values.ingress.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.ingress.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
data:
  route.sh: |
    #/bin/bash

    # NAME="cp-proxy"
    # NAMESPACE="ibm-common-services"
    # INGRESS_OPERATOR_NAMESPACE="openshift-ingress-operator"

    cp /opt/ingress-nginx/config/cp-proxy-route.yaml /opt/ingress-nginx/data/

    echo "Trying to delete the route ${NAME} first."
    kubectl -n ${NAMESPACE} delete -f /opt/ingress-nginx/data/cp-proxy-route.yaml

