# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ingress.name }}-route
  labels:
    app: {{ .Values.ingress.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.ingress.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: nginx-ingress-controller
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
data:
  cp-proxy-route.yaml: |
    # OCP route for ingress nginx#      
    ---
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: cp-proxy
      labels:
        app: {{ .Values.ingress.name }}
        component: {{ .Values.ingress.name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      host: cp-proxy.apps.ibm.com
      port:
        targetPort: https
      subdomain: ""
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: passthrough
      to:
        kind: Service
        name: nginx-ingress-controller
        weight: 100
      wildcardPolicy: None
    status:
      ingress: []          
