apiVersion: operator.ibm.com/v1alpha1
kind: NginxIngress
metadata:
  name: example
spec:
  ingress:
    name: nginx-ingress-controller
    replicaCount: 1
    hostNetwork: false
    hostPort: false
    httpPort: 80
    httpsPort: 443
    routeHost: cp-proxy.apps.ibm.com
    image:
      repository: ibmcom/nginx-ingress-controller
      tag: 0.23.0
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 256Mi 
    config:
      disable-access-log: 'true'
      keep-alive-requests: '10000'
      upstream-keepalive-connections: '64'
      server-tokens: 'false'
    extraArgs: {}
    annotations: {}
    nodeSelector: {}
    tolerations: []
  defaultBackend:
    name: default-http-backend
    replicaCount: 1
    image:
      repository: ibmcom/default-http-backend
      tag: 1.5.1
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
    nodeSelector: {}
    tolerations: []
  init:
    image:
      repository: ibmcom/icp-initcontainer
      tag: 1.0.0-build.1
      pullPolicy: IfNotPresent
  fips_enabled: false
