apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-ingress-nginx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-ingress-nginx-operator
  template:
    metadata:
      labels:
        name: ibm-ingress-nginx-operator
        app.kubernetes.io/managed-by: ""
        app.kubernetes.io/name: "ibm-ingress-nginx-operator"
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-ingress-nginx-operator
      containers:
        - name: ibm-ingress-nginx-operator
          image: quay.io/opencloudio/ibm-ingress-nginx-operator:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-ingress-nginx-operator"
            - name: INGRESS_IMAGE_DIGEST
              value: "quay.io/opencloudio/nginx-ingress-controller@sha256:54996a84c918eabca0c4ec7f91da203cfe7229c43615d41c1b3b2adc4c18629e"
            - name: DEFAULT_BACKEND_IMAGE_DIGEST
              value: "quay.io/opencloudio/default-http-backend@sha256:9e886cace21a0e9f3265d268e1ad652ae53030835cc0f095308b23dc5df62b6b"
            - name: KUBECTL_IMAGE_DIGEST
              value: "quay.io/opencloudio/kubectl@sha256:78b8c05746d6cdef32dbabd31ee7a658ad6ac15aec9939e14385dafffb4eb3ab"
