apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-ingress-nginx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-ingress-nginx-operator
  template:
    metadata:
      labels:
        name: ibm-ingress-nginx-operator
        app.kubernetes.io/managed-by: ""
        app.kubernetes.io/name: "ibm-ingress-nginx-operator"
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: "FREE"
    spec:
      serviceAccountName: ibm-ingress-nginx-operator
      containers:
        - name: ibm-ingress-nginx-operator
          image: quay.io/opencloudio/ibm-ingress-nginx-operator:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-ingress-nginx-operator"
            - name: INGRESS_IMAGE_DIGEST
              value: "quay.io/opencloudio/nginx-ingress-controller@sha256:1b9ca6c316f853cef939e5c4ec59c7a01081dd80712961358722a582a1ada842"
            - name: DEFAULT_BACKEND_IMAGE_DIGEST
              value: "quay.io/opencloudio/default-http-backend@sha256:2a5e3bfe7a771d36ad186e2ab8303ea2fbb854b4a7437e7c3b3f1d8e87d9e286"
            - name: INIT_IMAGE_DIGEST
              value: "quay.io/opencloudio/icp-initcontainer@sha256:9aad9fd724ec9308bec711d7738b5f0ae0c37a72ffb19a26dbcf622f1a603e89"
            - name: KUBECTL_IMAGE_DIGEST
              value: "quay.io/opencloudio/kubectl@sha256:deeb798aaa12142c95ba37bd90ae99ed112afda1170be321db8b1476c7ac9fdd"
