# Licensed Materials - Property of IBM
# Copyright IBM Corporation 2016,2021. All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Whether to enable FIPS
fips_enabled: false

# Config related with ingress nginx controller
ingress:
  name: nginx-ingress-controller
  replicaCount: 1
  replicas: 1
  hostNetwork: false
  hostPort: false
  httpPort: 7080
  httpsPort: 7443
  routeHost: ""
  imageRegistry: quay.io/opencloudio
  imageDigest: quay.io/opencloudio/nginx-ingress-controller@sha256:b1aa46ae49591025efea19dc894460433241943031b7c5221a549c0a5c163363
  image:
    repository: nginx-ingress-controller
    tag: 0.23.13
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 200m
      memory: 512Mi
  config:
    disable-access-log: 'true'
    keep-alive-requests: '10000'
    upstream-keepalive-connections: '64'
    server-tokens: 'false'
    ssl-ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256'
  extraArgs: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  watchNamespace: []

# Config related with default http backend
defaultBackend:
  name: default-http-backend
  replicaCount: 1
  replicas: 1
  imageRegistry: quay.io/opencloudio
  imageDigest: quay.io/opencloudio/default-http-backend@sha256:df00d527d36c67d8746f35d346edd600d2fb65db70ced420abc3de255eb51afd
  image:
    repository: default-http-backend
    tag: 1.5.8
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []

# The init image used to configure some system setting
init:
  imageDigest: quay.io/opencloudio/icp-initcontainer@sha256:60699eab29e17db05963ed19f8bbd0c6124b2b6d19c2d2563698660f9f46997e
  imageRegistry: quay.io/opencloudio
  image:
    repository: icp-initcontainer
    tag: 1.0.0-build.10
    pullPolicy: IfNotPresent

# The kubectl image used to patch route resource
kubectl:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  imageDigest: quay.io/opencloudio/kubectl@sha256:3aebec68f70b466d3e18a1bad8dd54c9220887a5fe1d779fb8a10aca4cbe3347
  imageRegistry: quay.io/opencloudio
  image:
    repository: kubectl
    tag: v1.15.9.5
